---
version: "3"

services:
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=nextcloud-db
    networks:
      - default

networks:
  default:
    driver: bridge
