---
version: "3"

services:
  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    ports:
       - "8082:8080"
    environment: 
      - ADMINER_DEFAULT_SERVER=wordpress-db