---
version: '3'

services:
  unifi:
    image: jacobalberty/unifi:v7.1.66
    container_name: unifi
    restart: unless-stopped
    volumes:
      - /var/docker/unifi:/unifi
      - /var/docker/unifi/backup:/unifi/data/backup
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    environment:
      - TZ="Europe/Berlin"
