version: "3.7"

services:
  guacamole_guacd:
    image: guacamole/guacd:latest
    container_name: guacamole_guacd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  guacamole_mysql:
    image: mysql:latest
    container_name: guacamole_mysql
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../volumes/guacamole/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=19IL!!fidDr4#61
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_sql
      - MYSQL_PASSWORD=Tr!n!dat#2
  guacamole_guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole_guacamole
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - MYSQL_HOSTNAME=guacamole_mysql
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_sql
      - MYSQL_PASSWORD=Tr!n!dat#2
      - GUACD_HOSTNAME=guacamole_guacd
      - GUACD_PORT=4822
    links:
      - guacamole_guacd:guacd
      - guacamole_mysql:mysql
    depends_on:
      - guacamole_guacd
      - guacamole_mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.guacamole-https.redirectscheme.scheme=https"
      - "traefik.http.routers.guacamole-http.entrypoints=web"
      - "traefik.http.routers.guacamole-http.rule=Host(`guacamole.stagge.it`)"
      - "traefik.http.routers.guacamole-http.middlewares=guacamole-https@docker"
      - "traefik.http.routers.guacamole.entrypoints=web-secure"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.stagge.it`)"
      - "traefik.http.routers.guacamole.tls=true"
      - "traefik.http.routers.guacamole.tls.certresolver=default"
      - "traefik.http.routers.guacamole.middlewares=secHeaders@file"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
    networks:
      - traefik_proxy
      - default

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
