version: "3.7"

services:
  traefik:
    image: traefik:2.3
    container_name: traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefikconfig:/etc/traefik
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.api.rule=Host(`traefik.stagge.it`)" 
      # - "traefik.http.routers.api.entryPoints=web"
      # - "traefik.http.routers.api.rule=PathPrefix(`/api`)  || PathPrefix(`/dashboard`))"
      # - "traefik.http.routers.api.service=api@internal"
      # - "traefik.http.routers.api.middlewares=api-auth"
      # - "traefik.http.middlewares.api-auth.basicauth.users=admin:$$2y$$05$$47WqfMIMjK7YfiDOVvbzaeVSkaeptMC0zx6E.zzBEgJ48vERJD7Ay"
      # - "traefik.http.services.api.loadbalancer.server.port=8080"
      ###########################################################################################
      - "traefik.http.routers.traefik.rule=Host(`traefik.stagge.it) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=web-secure"
      - "traefik.http.routers.traefik.tls.certresolver=default"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth@docker"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$05$$47WqfMIMjK7YfiDOVvbzaeVSkaeptMC0zx6E.zzBEgJ48vERJD7Ay" # Siehe Anleitung
    networks:
      - traefik_proxy
      - default
    ports:
      - "80:80"
      - "443:443"
    restart: always

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
