version: "3.7"

services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../volumes/portainer-ce/data:/data
    ports:
      - 9000:9000
    networks:
      - default
