version: '3.8'
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/var/lib/grafana:/var/lib/grafana
      - ./volumes/var/log/grafana:/var/log/grafana
