version: "3"

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_LEVEL= info
      - DOZZLE_TAILSIZE = 300
      # - DOZZLE_FILTER = "status=running"
      # - DOCKER_HOST = tcp://socket-proxy:2375
    ports:
      - 9999:8080
