version: '3.8'
watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --cleanup --label-enable
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # - WATCHTOWER_SCHEDULE=0 0 2 * *
      # - WATCHTOWER_NOTIFICATION=email
      # - WATCHTOWER_EMAIL_FROM=admin@posteo.de
      # - WATCHTOWER_EMAIL_TO=olaf.stagge@posteo.de
      # - WATCHTOWER_SERVER=smtp.posteo.de
      # - WATCHTOWER_SERVER_USER=olaf.stagge@posteo.de
      # - WATCHTOWER_SERVER_PASSWORD=123456
      # - WATCHTOWER_EMAIL_DELAY=2
      - WATCHTOWER_POLL_INTERVAL=120   #Poll interval in seconds, nicht zusammen mit WATCHTOWER_SCHEDULE
      - WATCHTOWER_CLEANUP=true
      # - WATCHTOWER_DEBUG=true
      - TZ=Europe/Berlin