---
version: '3'

services:
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    container_name: influxdb
    ports:
      - '8086:8086'
    volumes:
      - /var/docker/influxdb/db:/var/lib/influxdb
      - /var/docker/influxdb/backup:/var/lib/influxdb/backup
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
