version: "3.7"

services:
  adminer:
    image: adminer
    container_name: db_adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=wordpress-db
