---
version: "3"
services:
  db_recipes:
    image: postgres:14-alpine
    container_name: recipes_db
    restart: unless-stopped
    volumes:
      - /var/docker/recipes/postgresql/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    image: vabene1111/recipes
    container_name: recipes_web
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:ro
      - /var/docker/recipes/staticfiles:/opt/recipes/staticfiles
      - /var/docker/recipes/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - default

  nginx_recipes:
    image: nginx:mainline-alpine
    container_name: recipes_nginx
    restart: unless-stopped
    depends_on:
      - web_recipes
    env_file:
      - ./.env
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:ro
      - /var/docker/recipes/staticfiles:/static
      - /var/docker/recipes/mediafiles:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recipes.entrypoints=websecure"
      - "traefik.http.routers.recipes.rule=Host(`recipes.stagge.it`)"
      - "traefik.http.routers.recipes.tls=true"
      - "traefik.http.routers.recipes.tls.certresolver=default"
      - "traefik.http.routers.recipes.middlewares=secHeaders@file"
      - "traefik.http.services.recipes.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default

  adminer_recipes:
    image: adminer
    container_name: recipes_adminer
    restart: unless-stopped
    ports:
      - "8083:8080"
  #   environment:
  #     # https://github.com/wodby/adminer   http://192.168.178.20:8082/?server=nextcloud-db&username=nextcloud&db=nextcloud
  #     - ADMINER_DEFAULT_SERVER=recipes_db
  #     - ADMINER_DEFAULT_DB_DRIVER=PostgreSQL
  #     - ADMINER_DESIGN=nette #galkaev #nette #kahi #bueltge #rmsoft_blue # https://github.com/vrana/adminer/tree/master/designs  
  #     # - ADMINER_DEFAULT_DB_NAME=nextcloud   #funktioniert nicht 
  #     - ADMINER_PLUGINS=tables-filter tinymce
  #     # - MYSQL_ROOT_PASSWORD=example

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
