version: "3.7"
services:
    docs:
        image: docker.pkg.github.com/stolaf/mkdocker/my-docs:latest
        restart: always
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        ports:
            - 80:80
    watchtower:
        image: containrrr/watchtower
        command: --cleanup --label-enable
        restart: always
        volumes:
            - /var/run/docker.sock://var/run/docker.sock
            - ~/.docker/config.json:/jonfig.json
