---
version: '3.3'

services:
  nextcloud-db:
    image: mariadb:10.8
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/docker/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
      - default
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nextcloud-app:
    # image: nextcloud:22.2
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - /var/docker/nextcloud/app:/var/www/html
      - /media/data/docker/nextcloud/data:/var/www/html/data
      # - /var/docker/nextcloud/data:/var/www/html/data
    links:
      - nextcloud-db
    ports:
      - 8088:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_URL}`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=default"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,secHeaders@file"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav"
      - "traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=/remote.php/dav/"
    networks:
      - traefik_proxy
      - default

  nextcloud-cron:
    image: nextcloud
    container_name: nextcloud-cron
    restart: always
    volumes:
      - /var/docker/nextcloud/app:/var/www/html
      - /media/data/docker/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis

  nextcloud-adminer:
    image: adminer
    container_name: nextcloud-adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      # https://github.com/wodby/adminer   http://192.168.178.20:8082/?server=nextcloud-db&username=nextcloud&db=nextcloud
      - ADMINER_DEFAULT_SERVER=nextcloud-db
      - ADMINER_DEFAULT_DB_DRIVER=mysql
      - ADMINER_DESIGN=nette #galkaev #nette #kahi #bueltge #rmsoft_blue # https://github.com/vrana/adminer/tree/master/designs  
      # - ADMINER_DEFAULT_DB_NAME=nextcloud   #funktioniert nicht 
      - ADMINER_PLUGINS=tables-filter tinymce
      # - MYSQL_ROOT_PASSWORD=example

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
